Class User.NewClass2 Extends %Persistent
{

Storage Default
{
<Data name="NewClass2DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^User.NewClass2D</DataLocation>
<DefaultData>NewClass2DefaultData</DefaultData>
<IdLocation>^User.NewClass2D</IdLocation>
<IndexLocation>^User.NewClass2I</IndexLocation>
<StreamLocation>^User.NewClass2S</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}
